spring:
  application:
    name: "Spring-Data-JPA"
  main:
    banner-mode: off
  datasource:
    url: "jdbc:mysql://localhost:3306/<YOUR_DB_NAME>?"
    username: "<YOUR_DB_USERNAME>"
    password: "<YOUR_DB_PASSWORD>"
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: off
